cybersport/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace cybersport.Controllers
{
    public class SessionController : Controller
    {
        public IActionResult Index()
        {
            if (User.Identity.Name != null)
                HttpContext.Session.SetString("sessionUser", User.Identity.Name);
            else
                ViewData["noSession"] = "Please log in";
            return View();
        }

        public IActionResult About()
        {
            ViewData["session"] = HttpContext.Session.GetString("sessionUser");
            return View();
        }
    }
}

cybersport/Views/Session/About.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>About session</title>
</head>
<body>
    <div>
        @{
            if(@ViewData["session"] == null)
            {
                <h3>No session</h3>
            }
            else 
            {
                <h3>Session: @ViewData["session"]</h3>
            }
         }
    </div>
</body>
</html>

cybersport/Views/Session/Index.cshtml
@Html.ActionLink("About", "About", "Session")

<!DOCTYPE html>

<html>
<head>
    <title>Index session</title>
</head>
<body>
    <div>
        <h3> @ViewData["noSession"]</h3>

    </div>
    <div class="container">
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="col-2">User</div>
            <div class="col-4"><input type="text" id="userInput" /></div>
        </div>
        <div class="row">
            <div class="col-2">Message</div>
            <div class="col-4"><input type="text" id="messageInput" /></div>
        </div>
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="col-6">
                <input type="button" id="sendButton" value="Send Message" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <ul id="messagesList"></ul>
        </div>
    </div>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>
</body>
</html>